version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: symfony/filesystem
    versions:
    - 4.4.19
    - 4.4.20
  - dependency-name: symfony/browser-kit
    versions:
    - 4.4.19
  - dependency-name: symfony/process
    versions:
    - 4.4.19
  - dependency-name: symfony/css-selector
    versions:
    - 4.4.19
  - dependency-name: symfony/finder
    versions:
    - 4.4.19
  - dependency-name: symfony/event-dispatcher
    versions:
    - 4.4.19
  - dependency-name: symfony/dom-crawler
    versions:
    - 4.4.19
  - dependency-name: webmozart/assert
    versions:
    - 1.9.1
